<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.graphfoundation.ongdb</groupId>
        <artifactId>geequel-enterprise-parent</artifactId>
        <version>1.1.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>

    <artifactId>ongdb-geequel-compiled-expressions</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>ONgDB - Compiled Expressions</name>
    <description>ONgDB Geequel compiled expressions</description>
    <url>https://graphfoundation.org/projects/ongdb/${project.version}/${project.artifactId}</url>

    <scm>
        <connection>scm:git:git://github.com/graphfoundation/ongdb.git</connection>
        <developerConnection>scm:git:git@github.com:graphfoundation/ongdb.git</developerConnection>
        <url>https://github.com/graphfoundation/ongdb.git</url>
    </scm>

    <properties>
        <license-text.header>headers/GPL-3-header.txt</license-text.header>
        <moduleName>org.graphfoundation.ongdb.geequel.internal.runtime.compiled.expressions</moduleName>
    </properties>

    <licenses>
        <license>
            <name>GNU Affero General Public License, Version 3</name>
            <url>http://www.gnu.org/licenses/agpl-3.0-standalone.html</url>
            <comments>The software ("Software") developed and owned by Graph Foundation, Inc.
                (referred to in this notice as "Graph Foundation") is
                licensed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 to all
                third parties and that license is included below.
            </comments>
        </license>
    </licenses>

    <build>
        <plugins>
            <plugin>
                <groupId>org.scalastyle</groupId>
                <artifactId>scalastyle-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-reflect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.scalacheck</groupId>
            <artifactId>scalacheck_2.11</artifactId>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_2.11</artifactId>
        </dependency>
        <dependency>
            <groupId>org.scalautils</groupId>
            <artifactId>scalautils_2.11</artifactId>
        </dependency>
        <dependency>
            <groupId>org.graphfoundation.ongdb</groupId>
            <artifactId>ongdb-expressions-3.5</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.graphfoundation.ongdb</groupId>
            <artifactId>ongdb-geequel-interpreted-runtime</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.graphfoundation.ongdb</groupId>
            <artifactId>ongdb-geequel-physical-planning</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>